image:
  repository: "luchik/project2022"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  hostname: wordpress.k8s-20.sa

persistentVolumeClaim:
  storageSize: 10Gi

extraEnvs:
  - name: WORDPRESS_DB_HOST
    value: 192.168.202.20:3306
  - name: WORDPRESS_DB_NAME
    value: wordpress
  - name: WORDPRESS_DB_USER
    value: wordpress
  - name: WORDPRESS_DB_PASSWORD
    value: wordpress
  - name: WP_DEBUG_LOG
    value: wordpress
